#!/bin/bash
set -e

usage() { echo 'usage: github-secret <repository> <file> [file] ...'; exit; }

log() { echo -e "\e[38;5;82;4m${1}\e[0m \e[38;5;226m${@:2}\e[0m"; }
err() { echo -e "\e[38;5;196;4m${1}\e[0m \e[38;5;87m${@:2}\e[0m" >&2; }

[[ $1 == '-h' || $1 == '--help' || $# -lt 2 || ! -f $2 ]] && { usage; }
[[ -d secret-$1 ]] && { err abort secret-$1 already exists; exit; }

CWD=$(pwd)
TEMP=$(mktemp --directory)

log zip create archive.zip
zip --junk-paths -9 $TEMP/archive.zip ${@:2}

cd $TEMP

log openssl create secret
openssl aes-256-cbc -a -salt -pbkdf2 -iter 42 -in archive.zip -out secret

log create README.md
sed "s|{{REPOSITORY}}|$1|" \
    ~/.config/github-secret/README.md.tpl \
    > README.md

log create script.sh
sed --expression "s|{{REPOSITORY}}|$1|" \
    ~/.config/github-split/script.sh.tpl \
    > script.sh

mv $TEMP $CWD/split-$1
log created secret-$1

rm --force --recursive $TEMP
