#!/bin/bash
set -e

usage() { echo 'usage: github-secret <repository> <file> [file] ...'; exit; }

log()   { echo -e "\e[30;47m ${1^^} \e[0m ${@:2}"; }
info()  { echo -e "\e[48;5;28m ${1^^} \e[0m ${@:2}"; }
error() { echo -e "\e[48;5;196m ${1^^} \e[0m ${@:2}" >&2; }


[[ $1 == '-h' || $1 == '--help' || $# -lt 2 || ! -f $2 ]] && { usage; }

info create secret
[[ -d secret-$1 ]] && { error abort secret-$1 already exists; exit; }

CWD=$(pwd)
TEMP=$(mktemp --directory)

log zip create archive.zip
zip --junk-paths -9 $TEMP/archive.zip ${@:2}

cd $TEMP

log openssl create secret
openssl aes-256-cbc \
    -a \
    -salt \
    -pbkdf2 \
    -iter 42 \
    -in archive.zip \
    -out secret

log create README.md
sed "s|{{REPOSITORY}}|$1|" \
    ~/.config/github-secret/README.md.tpl \
    > README.md

log create install.sh
sed --expression "s|{{REPOSITORY}}|$1|" \
    ~/.config/github-secret/install.sh.tpl \
    > install.sh

rm archive.zip
mv $TEMP $CWD/secret-$1
info created secret-$1

rm --force --recursive $TEMP
